### PR TITLE
Name app as fork

### PR DESCRIPTION
**Pull request by licaon-kter**
...right?

### CODE REVIEW

**Comment by KaKi87** [comment]
Hello @patrickkostjens is your fork still maintained ? Thanks

**Comment by patrickkostjens** [comment]
Hi @KaKi87, no it’s not. Only saw this PR just now as well.

**Comment by KaKi87** [comment]
Regarding the PR itself I'd say it doesn't make sense to rename the Android app with `(fork)` because the end user doesn't care about that.

When intended to be maintained, though, creating a whole new name and logo for it would make sense.

Turns out your fork as been forked by [`vaavaa/Kandroid`](https://github.com/vaavaa/Kandroid), would you name it `Kanboard (fork) (fork)` ? :sweat_smile: 

However, its last commit, although more recent that yours, is still from last year, and the author didn't enabled the issues section either.

**Comment by licaon-kter** [comment]
Well, name your fork something else in general :)

**Pull request merged**
